name: Formatting check (run `pnpm format` locally if this fails)

on: pull_request

jobs:
    format-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: "23"
            - name: Install pnpm
              run: |
                  npm install -g pnpm
                  pnpm install
            - name: Run formatting script
              run: pnpm format
            - name: Fail if changes
              run: git diff --exit-code
